
/* eslint-disable no-template-curly-in-string */
const data = {
  moreInformationLabel: 'Mehr erfahren',
  filterField: {
    searchPage: '/content/zhweb/de/suche.html?q=${query}',
    noResultsLabel: 'Keine Resultate',
    searchInSiteSearchLabel: 'Gesamte Website nach «${query}» durchsuchen.',
  },
  pages: {
    topSection: {
      title: 'Regierungsrat',
      text: 'Text Text',
      link: 'content/zhweb/de/regierungsrat.html',
    },
    middleSection: [
      {
        path: '/content/zhweb/de/gesundheit.html',
        title: 'Volkswirtschaftdirektion',
        synonyms: ['Krankenversicherung', 'Gesundsheitsversorgung', 'Gesundsheitsberufe', 'Gesund bleiben'],
        subpages: [{
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Amt für Verkehr',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Amt für Wirtschaft und Arbeit',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Zürcher Verkehrsbund ZVV',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        }],
      },
      {
        path: '/content/zhweb/de/familie.html',
        title: 'Gesundheitsdirektion',
        synonyms: ['Partnerschaft', 'Eltern & Kinder', 'Unterstützung für Kinder & Jugendliche', 'Alter', 'Tod', 'Vormundschaft'],
        subpages: [{
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Kantonsapotheke Zürich',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Kantonale Heilmittelkontrolle Zürich',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Kantonales Labor Zürich',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Veterinäramt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Kantonale Ethikkommission',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        }],
      },
      {
        path: '/content/zhweb/de/soziales.html',
        title: 'Finanzdirektion',
        synonyms: ['Arbeitslosigkeit', 'Finanzielle Hilfen', 'Sozialversicherungen', 'Beratungsangebote', 'Soziale Einrichtungen'],
        subpages: [{
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Personalamt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Finanzverwaltung',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Amt für Informatik',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Kantonale Drucksachen- und Materialzentrale',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Steueramt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        }],
      },
      {
        path: '/content/zhweb/de/bildung.html',
        title: 'Direktion der Justiz und des Innern',
        synonyms: ['Bildungssystem', 'Schulen', 'Unterrichten', 'Schwierigkeiten in der Schule', 'Weiterbildung', 'Forschung', 'Bildungsgerechtigkeit'],
        subpages: [{
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Staatsanwaltschaft',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Jugendstrafrechtspflege',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Amt für Justizvollzug',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Gemeindeamt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Handelsregisteramt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Statistisches Amt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Staatsarchiv',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Kantonale Opferhilfstelle',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Fachstelle Gleichstellung',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Fachstelle Kultur',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Fachstelle Integration',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Statthalterämter und Bezirksratskanzleien',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        }],
      },
      {
        path: '/content/zhweb/de/sport-kultur.html',
        title: 'Sicherheitsdirektion',
        synonyms: ['Jugendsport', 'Sportförderung', 'Kulturpolitik', 'Kulturflrderung', 'Kulturpreise', 'Archäologie'],
        subpages: [{
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Sportamt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Kantonspolizei',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Strassenverkehrsamt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Migrationsamt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Amt für Militär und Zivilschutz',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Sozialamt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Passbüro',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        }],
      },
      {
        path: '/content/zhweb/de/wirtschaft-arbeit.html',
        title: 'Bildungsdirektion',
        synonyms: ['Arbeitsmarkt', 'Arbeitnehmer- & Arbeitgeberverhältnis', 'Schwarzarbeit'],
        subpages: [{
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Bildungsplanung',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Fachstelle für Schulbeurteilung',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Volksschulamt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Mittelschul- und Berufsbildungsamt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Hochschulamt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Amt für Jugend und Berufsberatung',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Lehrmittelverlag',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        }],
      },
      {
        path: '/content/zhweb/de/steuern.html',
        title: 'Baudirektion',
        synonyms: ['Steuererklärung', 'Steuern bezahlen', 'Grundlagen'],
        subpages: [{
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Amt für Landschaft und Natur',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Amt für Raumentwicklung',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Amt für Abfall, Wasser, Energie und Luft',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Hochbauamt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Immobilienamt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Tiefbauamt',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Leitstelle für Baubewilligungen',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Koordinationsstelle für Umweltschutz',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        }],
      },
      {
        path: '/content/zhweb/de/mobilität.html',
        title: 'Staatskanzlei',
        synonyms: ['Reisen: Pass & ID', 'Fahren lernen', 'Führerausweis', 'Fahrzeuge', 'Autonummern', 'Gesamtverkehr', 'Öffentlicher Verkehr'],
        subpages: [{
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Kommunikationsabteilung des Regungsrates',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Zentrale Dienste',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Personal und Finanzen',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Rechtsdienst',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'IT-, Projekt- und Prozess-Management',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Regierungscontrolling',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Digitale Verwaltung und E-Government',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        },
        {
          path: '/content/zhweb/de/gesundheit/sub.html',
          title: 'Koordination Aussenbeziehungen',
          keywords: 'Keyword 1, Keyword 2',
          synonyms: ['Syn 1', 'Syn 2'],
        }],
      },
    ],
    bottomSection: [{
      title: 'Kantonsrat',
      text: 'Der Kantonsrat ist die Legislative. Er beschliesst Gesetze und überwacht die Tätigkeiten des Regierungsrats.',
      link: 'content/zhweb/de/kantonsrat.html',
    },
    {
      title: 'Gerichte',
      text: 'Die Gerichte des Kantons Zürich sprechen Recht anhand der Gesetze auf kantonaler und nationaler Ebene. Das höchste Gericht des Kantons Zürich ist das Obergericht.',
      link: 'content/zhweb/de/gerichte.html',
    },
    {
      title: 'Gemeinden',
      text: '',
      link: 'content/zhweb/de/gemeinden.html',
    }],
  },
};

module.exports = data;
