/* eslint-disable no-template-curly-in-string */
const data = {
  moreInformationLabel: 'Mehr erfahren',
  filterField: {
    searchPage: '/content/zhweb/de/suche.html?q=${query}',
    noResultsLabel: 'Keine Resultate',
    searchInSiteSearchLabel: 'Gesamte Website nach «${query}» durchsuchen.',
  },
  pages: {
    topSection: {
      title: 'Regierungsrat',
      text: 'Text Text',
      link: 'content/zhweb/de/regierungsrat.html',
    },
    middleSection: [
      {
        path: '/content/zhweb/de/gesundheit.html',
        title: 'Volkswirtschaftdirektion lang',
        shortTitle: 'Volkswirtschaftdirektion',
        synonyms: [
          'Krankenversicherung',
          'Gesundsheitsversorgung',
          'Gesundsheitsberufe',
          'Gesund bleiben',
        ],
        subpages: [
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Amt für Verkehr lang',
            shortTitle: 'Amt für Verkehr',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Amt für Wirtschaft und Arbeit lang',
            shortTitle: 'Amt für Wirtschaft und Arbeit',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Zürcher Verkehrsbund ZVV lang',
            shortTitle: 'Zürcher Verkehrsbund ZVV',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
        ],
      },
      {
        path: '/content/zhweb/de/familie.html',
        title: 'Gesundheitsdirektion lang',
        shortTitle: 'Gesundheitsdirektion',
        synonyms: [
          'Partnerschaft',
          'Eltern & Kinder',
          'Unterstützung für Kinder & Jugendliche',
          'Alter',
          'Tod',
          'Vormundschaft',
        ],
        subpages: [
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Kantonsapotheke Zürich lang',
            shortTitle: 'Kantonsapotheke Zürich',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Kantonale Heilmittelkontrolle Zürich lang',
            shortTitle: 'Kantonale Heilmittelkontrolle Zürich',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Kantonales Labor Zürich lang',
            shortTitle: 'Kantonales Labor Zürich',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Veterinäramt lang',
            shortTitle: 'Veterinäramt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Kantonale Ethikkommission lang',
            shortTitle: 'Kantonale Ethikkommission',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
        ],
      },
      {
        path: '/content/zhweb/de/soziales.html',
        title: 'Finanzdirektion lang',
        shortTitle: 'Finanzdirektion',
        synonyms: [
          'Arbeitslosigkeit',
          'Finanzielle Hilfen',
          'Sozialversicherungen',
          'Beratungsangebote',
          'Soziale Einrichtungen',
        ],
        subpages: [
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Personalamt lang',
            shortTitle: 'Personalamt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Finanzverwaltung lang',
            shortTitle: 'Finanzverwaltung',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Amt für Informatik lang',
            shortTitle: 'Amt für Informatik',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Kantonale Drucksachen- und Materialzentrale lang',
            shortTitle: 'Kantonale Drucksachen- und Materialzentrale',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Steueramt lang',
            shortTitle: 'Steueramt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
        ],
      },
      {
        path: '/content/zhweb/de/bildung.html',
        title: 'Direktion der Justiz und des Innern lang',
        shortTitle: 'Direktion der Justiz und des Innern',
        synonyms: [
          'Bildungssystem',
          'Schulen',
          'Unterrichten',
          'Schwierigkeiten in der Schule',
          'Weiterbildung',
          'Forschung',
          'Bildungsgerechtigkeit',
        ],
        subpages: [
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Staatsanwaltschaft lang',
            shortTitle: 'Staatsanwaltschaft',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Jugendstrafrechtspflege lang',
            shortTitle: 'Jugendstrafrechtspflege',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Amt für Justizvollzug lang',
            shortTitle: 'Amt für Justizvollzug',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Gemeindeamt',
            shortTitle: 'Gemeindeamt lang',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Handelsregisteramt lang',
            shortTitle: 'Handelsregisteramt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Statistisches Amt lang',
            shortTitle: 'Statistisches Amt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Staatsarchiv lang',
            shortTitle: 'Staatsarchiv',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Kantonale Opferhilfstelle',
            shortTitle: 'asd',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Fachstelle Gleichstellung',
            shortTitle: 'asd',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Fachstelle Kultur lang',
            shortTitle: 'Fachstelle Kultur',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Fachstelle Integration lang',
            shortTitle: 'Fachstelle Integration',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Statthalterämter und Bezirksratskanzleien lang',
            shortTitle: 'Statthalterämter und Bezirksratskanzleien',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
        ],
      },
      {
        path: '/content/zhweb/de/sport-kultur.html',
        title: 'Sicherheitsdirektion lang',
        shortTitle: 'Sicherheitsdirektion',
        synonyms: [
          'Jugendsport',
          'Sportförderung',
          'Kulturpolitik',
          'Kulturflrderung',
          'Kulturpreise',
          'Archäologie',
        ],
        subpages: [
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Sportamt lang',
            shortTitle: 'Sportamt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Kantonspolizei lang',
            shortTitle: 'Kantonspolizei',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Strassenverkehrsamt lang',
            shortTitle: 'Strassenverkehrsamt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Migrationsamt lang',
            shortTitle: 'Migrationsamt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Amt für Militär und Zivilschutz lang',
            shortTitle: 'Amt für Militär und Zivilschutz',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Sozialamt lang',
            shortTitle: 'Sozialamt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Passbüro lang',
            shortTitle: 'Passbüro',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
        ],
      },
      {
        path: '/content/zhweb/de/wirtschaft-arbeit.html',
        title: 'Bildungsdirektion lang',
        shortTitle: 'Bildungsdirektion',
        synonyms: ['Arbeitsmarkt', 'Arbeitnehmer- & Arbeitgeberverhältnis', 'Schwarzarbeit'],
        subpages: [
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Bildungsplanung lang',
            shortTitle: 'Bildungsplanung',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Fachstelle für Schulbeurteilung lang',
            shortTitle: 'Fachstelle für Schulbeurteilung',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Volksschulamt lang',
            shortTitle: 'Volksschulamt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Mittelschul- und Berufsbildungsamt lang',
            shortTitle: 'Mittelschul- und Berufsbildungsamt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Hochschulamt lang',
            shortTitle: 'Hochschulamt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Amt für Jugend und Berufsberatung',
            shortTitle: 'asd',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Lehrmittelverlag lang',
            shortTitle: 'Lehrmittelverlag',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
        ],
      },
      {
        path: '/content/zhweb/de/steuern.html',
        title: 'Baudirektion lang',
        shortTitle: 'Baudirektion',
        synonyms: ['Steuererklärung', 'Steuern bezahlen', 'Grundlagen'],
        subpages: [
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Amt für Landschaft und Natur lang',
            shortTitle: 'Amt für Landschaft und Natur',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Amt für Raumentwicklung',
            shortTitle: 'asd',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Amt für Abfall, Wasser, Energie und Luft lang',
            shortTitle: 'Amt für Abfall, Wasser, Energie und Luft',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Hochbauamt lang',
            shortTitle: 'Hochbauamt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Immobilienamt lang',
            shortTitle: 'Immobilienamt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Tiefbauamt lang',
            shortTitle: 'Tiefbauamt',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Leitstelle für Baubewilligungen lang',
            shortTitle: 'Leitstelle für Baubewilligungen',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Koordinationsstelle für Umweltschutz lang',
            shortTitle: 'Koordinationsstelle für Umweltschutz',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
        ],
      },
      {
        path: '/content/zhweb/de/mobilität.html',
        title: 'Staatskanzlei lang',
        shortTitle: 'Staatskanzlei',
        synonyms: [
          'Reisen: Pass & ID',
          'Fahren lernen',
          'Führerausweis',
          'Fahrzeuge',
          'Autonummern',
          'Gesamtverkehr',
          'Öffentlicher Verkehr',
        ],
        subpages: [
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Kommunikationsabteilung des Regungsrates lang',
            shortTitle: 'Kommunikationsabteilung des Regungsrates',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Zentrale Dienste lang',
            shortTitle: 'Zentrale Dienste',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Personal und Finanzen lang',
            shortTitle: 'Personal und Finanzen',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Rechtsdienst lang',
            shortTitle: 'Rechtsdienst',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'IT-, Projekt- und Prozess-Management lang',
            shortTitle: 'IT-, Projekt- und Prozess-Management',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Regierungscontrolling lang',
            shortTitle: 'Regierungscontrolling',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Digitale Verwaltung und E-Government lang',
            shortTitle: 'Digitale Verwaltung und E-Government',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
          {
            path: '/content/zhweb/de/gesundheit/sub.html',
            title: 'Koordination Aussenbeziehungen lang',
            shortTitle: 'Koordination Aussenbeziehungen',
            keywords: 'Keyword 1, Keyword 2',
            synonyms: ['Syn 1', 'Syn 2'],
          },
        ],
      },
    ],
    bottomSection: [
      {
        title: 'Kantonsrat',
        text: 'Der Kantonsrat ist die Legislative. Er beschliesst Gesetze und überwacht die Tätigkeiten des Regierungsrats.',
        link: 'content/zhweb/de/kantonsrat.html',
      },
      {
        title: 'Gerichte',
        text: 'Die Gerichte des Kantons Zürich sprechen Recht anhand der Gesetze auf kantonaler und nationaler Ebene. Das höchste Gericht des Kantons Zürich ist das Obergericht.',
        link: 'content/zhweb/de/gerichte.html',
      },
      {
        title: 'Gemeinden',
        text: '',
        link: 'content/zhweb/de/gemeinden.html',
      },
    ],
  },
};

module.exports = data;
