const data = {
  data: [
    {
      link: '/steuerbuch/steuerbuch/zstb-21-3.html',
      themenbereich: 'Natürliche Personen',
      titel: 'Weisung der Finanzdirektion betreffend Gewährung eines Einschlages auf dem Eigenmietwert in Härtefällen',
      erlassdatum: '21. Juni 1999',
      'gueltig-ab': '1. Januar 1999',
      'zstb-nummer': '21.3',
      'nummer-alt': '15/720',
    },
    {
      link: '/steuerbuch/steuerbuch/zstb-22-2.html',
      themenbereich: 'Natürliche Personen',
      titel: 'Merkblatt des kantonalen Steueramtes zur Steuerbarkeit von Renten und Kapitalleistungen',
      erlassdatum: '9. Dezember 2009',
      'gueltig-ab': '1. Dezember 2009',
      'zstb-nummer': '22.2',
      'nummer-alt': '16/013',
    },
    {
      link: '/steuerbuch/steuerbuch/zstb-45-1.html',
      themenbereich: 'Natürliche Personen',
      titel: 'Vermögenssteuer bei rückkaufsfähigen Rentenversicherungen während der Rentenlaufzeit (Praxishinweis)',
      erlassdatum: '23. August 2012',
      'gueltig-ab': '23. August 2012',
      'zstb-nummer': '45.1',
      'nummer-alt': '',
    },
    {
      link: '/steuerbuch/steuerbuch/zstb-21-3.html',
      themenbereich: 'Verfahrensrecht',
      titel: 'Weisung der Finanzdirektion über die Mitwirkung der Gemeindesteuerämter bei der Vorbereitung der Steuereinschätzung ab 2011 natürlicher Personen (ab Steuererklärung 2011)',
      erlassdatum: '21. Juni 1999',
      'gueltig-ab': '1. Januar 1999',
      'zstb-nummer': '54.3',
      'nummer-alt': '15/720',
    },
    {
      link: '/steuerbuch/steuerbuch/zstb-22-2.html',
      themenbereich: 'Verfahrensrecht',
      titel: 'Weisung der Finanzdirektion über die Einschätzung der Staats- und Gemeindesteuern und der direkten Bundessteuer natürlicher Personen ab Kalenderjahr 2011 durch die Gemeindesteuerämter',
      erlassdatum: '9. Dezember 2003',
      'gueltig-ab': '1. Dezember 2003',
      'zstb-nummer': '54.4',
      'nummer-alt': '16/013',
    },
    {
      link: '/steuerbuch/steuerbuch/zstb-45-1.html',
      themenbereich: 'Verfahrensrecht',
      titel: 'Weisung der Finanzdirektion über die elektronische Erfassung und Aufbewahrung von Steuerakten sowie die Vernichtung von Papierakten (ab Steuerperiode 2007)',
      erlassdatum: '23. August 2015',
      'gueltig-ab': '23. August 2012',
      'zstb-nummer': '54.5',
      'nummer-alt': '',
    },
  ],
  numberOfResults: 12,
  numberOfResultPages: 2,
};

module.exports = data;
